#app端口
port: 8080
appName: demo
log:
  level: DEBUG
  stdout: true

##################################
mysql:
  default:
    addr: "127.0.0.1:3306"
    database: dem0
    user: "user"
    password: "pwd"

redis:
  default:
    addr: "127.0.0.1:6379"
    db: 1
